### ISSUE TITLE
GTA VC Controller Code Input not working

### ISSUE THREAD

**Issue by Smoker1** [GTAmodding/re3#1131] opened 2021-02-18 21:03 UTC
**Describe the bug**
Unable to Input Controller Codes. I can get only a couple Codes to Input Correctly, but certain desired Codes will not work.

PSVita Build. Latest Available.

**Comment by AGraber** [comment] 2021-02-19 08:23
Duplicate of #1078

**Closed** 2021-02-19 08:33 UTC
