### ISSUE TITLE
save files cannot be loaded (constant crash) after completing Paramedic missions

### ISSUE THREAD

**Issue by ZiUlzimaze** [GTAmodding/re3#1140] opened 2021-02-19 15:44 UTC
**Describe the bug**
After completing level 12 of the Paramedic Mission and getting the health,adrenaline, and infinite stamina, the game continues on as usual. But upon saving the game and reloading it after, the game crashes with a pop-up box stating
"Assertion Failed!
File: D:\a\re3\re3\src\control\Garages.cpp
Line: 1761
Function: CGarage::FindDoorsEntities
Expression: xstart < = xend

(Press Retry to debug the application)
--end--
*Note: other missions don't "corrupt" the save file after completion

**Screenshots**
![Screenshot (37)](https://user-images.githubusercontent.com/79324134/108525958-92395f00-730b-11eb-992c-c59c7be2d90b.png)

**Version**
Re3 :Win 64-bit D3D9 OAL a4412e8

**Comment by Grovespaz** [comment] 2021-02-19 18:45
Probable duplicate of https://github.com/GTAmodding/re3/issues/1125

**Comment by erorcun** [comment] 2021-06-28 11:54
Duplicate. We know how to solve it, but it will need time

**Closed by erorcun** 2021-06-28 11:54 UTC
Labels: bug, duplicate

**Comment by aeifr** [comment] 2021-06-28 16:33
@erorcun 
Is there any guide how to or already a tool to fix this tiny issue?
Or is someone already working on a fix?

**Comment by withmorten** [comment] 2021-06-28 16:36
the problem is incompatible saves and the garages save sizeof hardcoded to a specific size that's unrelated to the actual number of bytes written. we already have compatible saves for windows/linux 32bit/64bit implemented in a PR by me (#1149) but this makes all old linux saves incompatible, and of course doesn't help with preexisting 64bit saves. we have also found a way to detect linux/windows incompability and 32/64bit incompability, but we don't have any code in re3 that fixes them yet. that's being worked on though.
