### ISSUE TITLE
Game crashes when walking or driving around in the Vice City Beach

### ISSUE THREAD

**Issue by Achilleas117** [GTAmodding/re3#928] opened 2021-01-05 09:40 UTC
I went into the beach of Vice City and i just walking or driving around in this place, but suddenly the game usually crashes while i walking or driving around the place and took out a ''reVC.exe has stopped working'' message. I have the miami branch of the re3 as of 5/1/2021 (latest) and running on Windows 10. Can someone fix this problem?
![GTA_ Vice City 5_1_2021 11_19_48 πμ](https://user-images.githubusercontent.com/76263103/103630531-768c1c00-4f4a-11eb-8a71-710ea44479fd.png)

**Comment by ttyborg** [comment] 2021-01-07 22:38
I can confirm this bug is also happening on Manjaro Linux.
reVC Git version c423c59

When it crashes, gdb outputs this:
```
RE3 ASSERT FAILED
        File: ../src/audio/sampman_oal.cpp
        Line: 1397
        Function: GetSampleBaseFrequency
        Expression: nSample < TOTAL_AUDIO_SAMPLES
reVC_debug_amd64_c423c59: ../src/core/re3.cpp:806: void re3_assert(const char*, const char*, unsigned int, const char*): Assertion `false' failed.

Thread 1 "reVC_debug_amd6" received signal SIGABRT, Aborted.
0x00007ffff76b5615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff76b5615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff769e862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff769e747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff76adbf6 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00005555558d89ac in re3_assert (expr=0x5555559c968d "nSample < TOTAL_AUDIO_SAMPLES", 
    filename=0x5555559c9426 "../src/audio/sampman_oal.cpp", lineno=1397, 
    func=0x5555559c9676 "GetSampleBaseFrequency") at ../src/core/re3.cpp:806
#5  0x00005555558e1aeb in cSampleManager::GetSampleBaseFrequency (this=0x555555eb6780 <SampleManager>, 
    nSample=4290985943) at ../src/audio/sampman_oal.cpp:1397
#6  0x0000555555583cfe in cAudioManager::SetUpOneShotCollisionSound (this=0x555555ab6380 <AudioManager>, col=...)
    at ../src/audio/AudioCollision.cpp:304
#7  0x0000555555584440 in cAudioManager::ServiceCollisions (this=0x555555ab6380 <AudioManager>)
    at ../src/audio/AudioCollision.cpp:384
#8  0x00005555555aaa39 in cAudioManager::ServiceSoundEffects (this=0x555555ab6380 <AudioManager>)
    at ../src/audio/AudioManager.cpp:471
#9  0x00005555555a9c13 in cAudioManager::Service (this=0x555555ab6380 <AudioManager>)
    at ../src/audio/AudioManager.cpp:119
#10 0x00005555556757c4 in cDMAudio::Service (this=0x555555ac6ee4 <DMAudio>) at ../src/audio/DMAudio.cpp:26
#11 0x00005555558d0a1a in Idle (arg=0x1) at ../src/core/main.cpp:1431
#12 0x00005555558d10cb in AppEventHandler (event=rsIDLE, param=0x1) at ../src/core/main.cpp:1668
#13 0x00005555558e6635 in RsEventHandler (event=rsIDLE, param=0x1) at ../src/skel/skeleton.cpp:212
#14 0x00005555558ccf91 in main (argc=1, argv=0x7fffffffde58) at ../src/skel/glfw/glfw.cpp:1928
```

**Comment by Sergeanur** [comment] 2021-01-07 22:48
Should be fixed now

**Comment by ttyborg** [comment] 2021-01-07 23:06
Yes, it seems to be fixed. Thanks!

**Closed** 2021-01-12 23:25 UTC
