### ISSUE TITLE
mp3s not being detected

### ISSUE THREAD

**Issue by kattjevfel** [GTAmodding/re3#852] opened 2020-11-29 14:48 UTC
Tried giving the "MP3 Player" feature a go, but unless I'm supposed to manually add them to a list somewhere, it doesn't appear to work.

I see this in the log:
```
[DBG-2]: Finding MP3s...
[DBG-2]: /home/katt/.local/share/Steam/steamapps/common/Grand Theft Auto 3\MP3\
```

Which made me think the path was just being messed up, I changed the `\\` to `/` and renamed the directory to be all uppercase, but even after re-compiling I couldn't get it working. Radio station doesn't show up.

This is on linux, if it wasn't clear, debug build.

**Comment by erorcun** [comment] 2020-11-29 14:51
works on my Ubuntu 20.04. please list your song file names, your distro and your system language

**Comment by kattjevfel** [comment] 2020-11-29 14:52
> works on my Ubuntu 20.04. please list your song file names, your distro and your system language

I'm running Arch Linux, I've renamed my track to `test.mp3` and my system is set to en_GB.UTF-8

**Comment by ByCybernetik** [comment] 2021-01-18 21:48
I have earned an MP3 player after renaming the folder "Grand Theft Auto 3" in " GTA 3"

**Comment by erorcun** [comment] 2021-06-28 15:13
yeah this was caused by small path variable size, should be fixed now.

**Closed by erorcun** 2021-06-28 15:13 UTC
