### ISSUE TITLE
[LCS] Crash when transitioning from hand-to-hand animation to kicking downed enemies

### ISSUE THREAD

**Issue by hazelnot** [GTAmodding/re3#1012] opened 2021-01-30 12:54 UTC
The game crashes when, after punching an NPC enough so they fall to the ground, the player attacks the NPC again, when the game would transition to ANIM_KICK_FLOOR.

gdb log:
`Thread 1 "reLCS" received signal SIGSEGV, Segmentation fault.
CAnimManager::BlendAnimation (clump=0x5555579a5a90, groupId=groupId@entry=ASSOCGRP_UNARMED, animId=animId@entry=ANIM_KICK_FLOOR, 
    delta=delta@entry=8) at /home/runner/work/re3/re3/src/animation/AnimManager.cpp:1392
1392	/home/runner/work/re3/re3/src/animation/AnimManager.cpp: No such file or directory.`

**Comment by Sergeanur** [comment] 2021-07-22 23:12
This is well known and caused by unreversed PedFight. Closing since it's not something that should be looked at yet.

**Closed by Sergeanur** 2021-07-22 23:12 UTC
Labels: bug, lcs
