### ISSUE TITLE
No audio hardware

### ISSUE THREAD

**Issue by pseregiet** [GTAmodding/re3#671] opened 2020-07-31 19:38 UTC
I'm on arch linux and there is no sound. In the options it says No sound hardware. I see no sound related logs/errors in the terminal when I run the game. The building didn't mention anything missing either. Can't find anything on google thanks to the awesome generic 're3' name poping up resident evil3.

**Comment by ShFil119** [comment] 2020-07-31 19:53
how do you build?

**Comment by pseregiet** [comment] 2020-07-31 20:21
./premake5Linux --with-librw gmake2
cd build
make config=release_linux-amd64-librw_gl3_glfw-oal -j8

**Comment by ShFil119** [comment] 2020-07-31 20:56
Can you try debug, then run from console and past here output?

**Comment by pseregiet** [comment] 2020-08-01 12:08
[oxi@new-host-2 gta3]$ ./re3-debug
[DBG]: cdvd_stream: read info 0x55f2cd87f010
[DBG]: Using one streaming thread for all channels
[DBG]: Created cdstream thread
[DBG-2]: [../src/skel/glfw/glfw.cpp.psInitialize:353]: gGameState = GS_START_UP
[DBG-2]: Default skin set as no other skins are available OR saved skin not found!
[DBG]: Physical memory size 3920760832
[DBG]: Available physical memory 2844282880
version 4.6 (Core Profile) Mesa 20.1.4
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1589]: gGameState = GS_INIT_ONCE
[DEV]: release_existing()
[DBG]: Initialising CTimer...
[DBG-2]: Performance counter not available, using millesecond timer

[DBG]: CTimer ready
[DBG]: Initialising CPedStats...
[DBG]: Loading pedstats data...
[DBG]: CPedStats ready
[DBG]: Intialising CTimeCycle...
[DBG]: CTimeCycle ready
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1616]: gGameState = GS_INIT_FRONTEND;
[DBG-2]: [../src/skel/glfw/glfw.cpp.main:1637]: gGameState = GS_FRONTEND;
LOAD frontend
LOAD sprite
[DBG-2]: STARTED PLAYING FRONTEND AUDIO TRACK
[DBG-2]: FRONTEND AUDIO TRACK STOPPED
[DBG-2]: STARTED PLAYING FRONTEND AUDIO TRACK

This is me going to the audio settings

**Comment by ShFil119** [comment] 2020-08-01 12:30
Sounds like something with your OS. (I'm also using arch and have no issue.)

Can you try "OpenAL: No sound in applications that use OpenAL" from: https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture/Troubleshooting#Applications

**Comment by pseregiet** [comment] 2020-08-01 16:36
That did not help. And for the record pulse audio and alsa both work with SDL based programs for example. I don't know if I have any other OpenAL based program but I will try that also

**Comment by ShFil119** [comment] 2020-08-01 16:44
We use here glfw, so it can behave different than sdl based programs.

**Comment by pseregiet** [comment] 2020-08-01 16:56
I know I know, I'm just saying I have no audio problems in any other game or program, with Pulse driver or alsa driver. I will try to find another OpenAL game and see if that works.

**Comment by pseregiet** [comment] 2020-08-01 21:50
ioquake3 uses openAL and I have sound

**Comment by QuestionableTrifle** [comment] 2020-10-04 17:47
I'd like to +1 the same issue, but for me this problem only exists with reVC; re3 has no problems with audio at all and lists my hardware as OpenAL Soft (plus additional EAX options are available, and also work).

Additional info:

* I have the original, 1.0, PC CD-ROM release of the game that I bought in 2003.
* I've compiled both re3 and reVC branches the same way (release, amd64).
* The re3 build is approximately 5 days old, but the reVC build is from today (approx 30 mins prior to writing this)
* My OS is debian Sid, kernel 5.8.0-2-amd64 and my actual audio hardware is an integrated RealTek ALC1220 codec.
* Pulse Audio is running quite happily and I have had no audio problems at all, with anything, since building this machine 2 years ago.
* The correct audio output is selected under GNOME's audio settings.
* Nothing relating to reVC or re3 is present in the syslog journal.
* The only other thing of note is that the re3 console output is significantly longer than that of reVC, and this is due to re3 itemising the sample rate and sample count of detected .wav files, whereas reVC is not doing this. I've attached the console output for both games.
* All of the audio files are, of course, present and I've also copied the audio from the Play disc to the 'audio' directory for both games, as well.
* For Vice City, I have a mixture of .wav files and .mp3 files. The .wavs are from the base installation and the .mp3 files are from the Play disc. I have not modified them in any way; this is exactly how they are on the installation CDs.
* I can play both the .wavs and .mp3s my OS without any problems using totem.


I'm not sure what else of note I can add. I'm happy try any suggestions and report back.

Thanks!

[re3_console_output.txt](https://github.com/GTAmodding/re3/files/5323894/re3_console_output.txt)
[reVC_console_output.txt](https://github.com/GTAmodding/re3/files/5323895/reVC_console_output.txt)

**Comment by Calinou** [comment] 2020-10-04 18:17
I can reproduce this on Fedora 31, but *only* with reVC (`miami` commit https://github.com/GTAmodding/re3/commit/9d53b738cc064f722cf18f37515daeb1fa8e443d), not re3 (`master` branch). Sound and music play just fine in re3.

**Comment by ShFil119** [comment] 2020-10-04 19:03
Case sensitivity strikes again. As quick fix you can rename folder `Audio` to `audio`.

**Comment by pseregiet** [comment] 2020-10-04 19:13
> Case sensitivity strikes again. As quick fix you can rename folder `Audio` to `audio`.

Indeed, I had my folder called AUDIO. Renaming to audio fixed the problem.

**Comment by Calinou** [comment] 2020-10-04 20:08
@ShFil119 That works, thanks!

I've used the data files from the Steam version. Would it be possible to check for `Audio` in addition to `audio` to make Steam data work out of the box?

**Comment by QuestionableTrifle** [comment] 2020-10-04 20:25
Partial success! After renaming the folder general sound effects are now present but the radio stations aren't playing, even though the station .adf files are found and loaded. The radio volume is at the default level in the audio settings. I've attached another log which may or may not be relavent because it shows reVC accessing vrock many times, despite vrock not playing back.

@Calinou Out of curiosity, are the radio stations in the Steam version also .adf files?

**Comment by QuestionableTrifle** [comment] 2020-10-04 20:53
Another small detail to add:

I started a new game just to drive around and admire Vice City in 4K. The road closure, storm warning clip played and then, subsequently, the radio audio played! I then tried changing stations but only to have the silence return once more.

**Comment by erorcun** [comment] 2020-10-04 22:31
Audio folder case sensitivity issue is fixed now. radios not playing issue is related with reVC being still WIP.

**Comment by Calinou** [comment] 2020-10-04 22:34
@QuestionableTrifle Yes:

```
~/.local/opt/gta-vc/audio
❯ ll *.adf
Permissions Size User Date Modified Name
.rwxrwxr-x   56M hugo 29 Sep 22:07  EMOTION.adf
.rwxrwxr-x   59M hugo 29 Sep 22:07  ESPANT.adf
.rwxrwxr-x   60M hugo 29 Sep 22:07  FEVER.adf
.rwxrwxr-x   57M hugo 29 Sep 22:07  FLASH.adf
.rwxrwxr-x   49M hugo 29 Sep 22:08  KCHAT.adf
.rwxrwxr-x   41M hugo 29 Sep 22:08  VCPR.adf
.rwxrwxr-x   74M hugo 29 Sep 22:08  VROCK.adf
.rwxrwxr-x   63M hugo 29 Sep 22:08  WAVE.adf
.rwxrwxr-x   65M hugo 29 Sep 22:08  WILD.adf
```

**Comment by erorcun** [comment] 2020-10-05 11:05
now fixed fully.

**Closed by erorcun** 2020-10-05 11:05 UTC
