### ISSUE TITLE
[Request] Switching monitor output in option menu

### ISSUE THREAD

**Issue by Tomasak** [GTAmodding/re3#1177] opened 2021-06-29 20:21 UTC
Switching output to different monitor (like from primary to television). Many games nowadays supports it.

**Comment by asm95** [comment] 2021-07-01 01:16
You can use the windowed mode and move it to the secondary monitor. That's for sure an modern enhancement but for now the team is focused in fixing bugs and progressing with LCS. Thanks for the report.

**Comment by Sergeanur** [comment] 2021-07-22 23:11
Closing as this is duplicate of #905

**Closed by Sergeanur** 2021-07-22 23:11 UTC
Labels: duplicate, enhancement
