### ISSUE TITLE
Linux release build cannot control game

### ISSUE THREAD

**Issue by parkerlreed** [GTAmodding/re3#710] opened 2020-09-25 18:30 UTC
Menus work fine but after loading the game it acts like I'm holding both the left and right sticks on a controller. There is no controller plugged in. This makes it impossible to play.

https://streamable.com/h27cxl

Arch Linux
Latest commit as of now 6dfb32d285f40bbae86322689e24775343dfd626

**Comment by ShFil119** [comment] 2020-09-25 19:05
It looks like something is introducing input into the game. If it's laptop can you try to disable trackpad?

(also using arch, but I can't reproduce)

**Comment by ga2mer** [comment] 2020-09-25 19:54
Same thing, nothing connected to PC except usb mouse and ps/2 keyboard
If gamepad connected, camera spinning to left instead of walking
Fixed for me if I comment these lines
https://github.com/GTAmodding/re3/blob/miami/src/skel/glfw/glfw.cpp#L1950-L1954

**Comment by erorcun** [comment] 2020-09-25 20:04
this is fault of glfw/sdl gamepad database, it sees your keyboard as gamepad. this is why we have `IsThisJoystickBlacklisted` func. in that file.

can you post what does `glfwGetJoystickName` return on your side?

**Comment by ga2mer** [comment] 2020-09-25 20:05
```
joyname is COMPANY USB Device System Control
joyname is COMPANY USB Device Consumer Control
```

**Comment by parkerlreed** [comment] 2020-09-25 22:23
How would I run that glfw function?

Is there any reason this isn't using the SDL2 game controller database? Everything else I use that implements input from SDL2 itself, haven't have any weird issues with.

And as @ga2mer points out this seems to be affecting normal gamepads as well.

**Comment by parkerlreed** [comment] 2020-09-25 22:30
Oh I was mistaken thinking this projected used SDL2 as the base. That would explain that. 

Yeah I think either my keyboard or touchpad much be showing up as a joysrick to glfw. 

Commenting out the lines as noted above does let me play with mouse/keybvoard.

**Comment by erorcun** [comment] 2020-09-25 22:37
you can print it to console. just remove the `#if 0` wrapper around the AllocConsole in glfw.cpp

then I'll blacklist those "joystick"s. this is certainly glfw problem.

**Comment by parkerlreed** [comment] 2020-09-25 22:47
```
joyname is Synaptics TM2438-005
joyname is ELAN Touchscreen
joyname is Primax Electronics, Ltd HP Wireless Keyboard Mouse Kit Consumer Control
```

I'd say probably regex blacklist Synaptcis, Touch, and Consumer

**Comment by erorcun** [comment] 2020-09-27 01:45
Should be fixed.

**Comment by parkerlreed** [comment] 2020-09-28 03:31
Got another.

```
joyname is touchscreen
```

Also is there a guide for manually mapping a controller that isn't supported but is a valid input?

**Comment by erorcun** [comment] 2020-09-28 06:51
Ok, looks like this problem only happens on OSes other than Windows, so I'll accept all "joystick"s on Windows, and accept the ones only registered on SDL gamepad DB on Linux etc., and removing the blacklist.

> Tried to map in the redefine controls and the buttons aren't registered. Only the right stick works in game.

This may be due to it tries to remap "touchscreen", I'll be waiting feedback after I merged the fix.

**Comment by ZLau92** [comment] 2020-09-30 06:15
I had the same problem. It looks like it was seeing my mouse as a joypad.
`joyname is Razer Razer Naga 2014`

**Comment by erorcun** [comment] 2020-10-04 19:25
Sorry for the delay, we've decided to add 'Detect joystick' menu just for that.
Now game will *only* rely on SDL gamepad DB on other OSes except Windows, and if you don't have one of the joysticks on that list you'll have to enter Controller->Detect joystick and press any button on your joystick.
Then game will save it in `re3.ini`, along with our other new settings.

**Closed by erorcun** 2020-10-04 19:25 UTC

**Comment by parkerlreed** [comment] 2020-10-05 18:35
Something's still up. Just compiled the latest master and while it doesn't spin like crazy, I'm always moving left. Tried rebinding controls but D for right is punching?

**Comment by erorcun** [comment] 2020-10-05 19:08
what Controller->Deteck Joystick says for your detected joystick?

**Comment by parkerlreed** [comment] 2020-10-05 19:19
Is there a hidden menu I'm missing? I don't see that on Release. Ok found it under a corrupt menu label (side note how do I fix those labels?)

![image](https://user-images.githubusercontent.com/841440/95122117-09d06e00-071e-11eb-8174-51f31415ca60.png)

![image](https://user-images.githubusercontent.com/841440/95122161-18b72080-071e-11eb-82f4-f8865d02bf6c.png)

**Comment by parkerlreed** [comment] 2020-10-05 19:24
(Oh the gamefiles were needed. Fixed the text)

It seems to use my keyboard as joystick? I;m just wanting to test keyboard/mouse input at the moment.

**Comment by parkerlreed** [comment] 2020-10-05 19:29
https://streamable.com/d2uxya

**Comment by erorcun** [comment] 2020-10-05 19:32
it seems someone added your keyboard to SDL gamepad DB :smile: you should defintiely open a issue in https://github.com/gabomdq/SDL_GameControllerDB

I'll blacklist your keyboard in my next PR until next GLFW version will have it fixed.

**Comment by parkerlreed** [comment] 2020-10-05 19:35
Weird I don't see it in either the built in SDL or the user curated database.

It's definitely not showing up in SDL

```
[parker@stealth Documents]$ controllermap 
INFO: There are 0 joysticks attached
INFO: 

Usage: ./controllermap number
For example: ./controllermap 0
Or: ./controllermap 0 >> gamecontrollerdb.txt
```

**Comment by parkerlreed** [comment] 2020-10-05 19:36
If I mash some keys on that controller menu in re3, I can seemingly map it to my mouse as well. It's accepting any input source you give it, not just controllers.

**Comment by parkerlreed** [comment] 2020-10-05 19:37
![image](https://user-images.githubusercontent.com/841440/95123902-abf15580-0720-11eb-8adb-535a56c50a75.png)

**Comment by parkerlreed** [comment] 2020-10-05 19:40
If I connect an actual controller, it works great with controller and mouse and keyboard.

So the issue seems to be that controller detect option accepting all inputs instead of just the database mapped.

**Comment by erorcun** [comment] 2020-10-05 19:43
(you can edit your posts)

then it's certainly GLFW bug, this is the only function that filters the controllers, you can see it in `glfw.cpp`:

```cpp
bool IsThisJoystickBlacklisted(int i)
{
#ifndef DONT_TRUST_RECOGNIZED_JOYSTICKS
	return false;
#else
	if (glfwJoystickIsGamepad(i))
		return false;

	const char* joyname = glfwGetJoystickName(i);

	if (strncmp(joyname, gSelectedJoystickName, strlen(gSelectedJoystickName)) == 0)
		return false;

	return true;
#endif
}
```

since you're seeing that menu, you have `DONT_TRUST_RECOGNIZED_JOYSTICKS` enabled. only conditions determine which controller is trusted are if `glfwJoystickIsGamepad()`, or `if (strncmp(joyname, gSelectedJoystickName, strlen(gSelectedJoystickName)) == 0)`, and `gSelectedJoystickName` is detected via that menu (and initially loaded from re3.ini).

To me it's certain that this is a bug involving GLFW/Arch Linux, and I consider opening an issue soon.

**Comment by ZLau92** [comment] 2020-10-05 19:54
I'll note that I encountered the problem on Linux Mint 20 (Ubuntu)

**Comment by erorcun** [comment] 2020-10-05 20:02
@parkerlreed 
is adding gSelectedJoystickName[0] && check before strncmp and deleting re3.ini fixes your problem?

**Comment by parkerlreed** [comment] 2020-10-05 20:02
Edited posts don't work for email users :)

That worked!

```
bool IsThisJoystickBlacklisted(int i)
{
#ifndef DONT_TRUST_RECOGNIZED_JOYSTICKS
        return false;
#else
        if (glfwJoystickIsGamepad(i))
                return false;

        const char* joyname = glfwGetJoystickName(i);

        if (gSelectedJoystickName[0] && strncmp(joyname, gSelectedJoystickName, strlen(gSelectedJoystickName)) == 0)
                return false;

        return true;
#endif
}
```

It still shows the name in the menu but ignored it correctly. Still works with actual controller as well.

**Comment by erorcun** [comment] 2020-10-05 20:06
oh what a shame :/ ok I'll push the fix soon. thanks!

**Comment by erorcun** [comment] 2020-10-17 15:13
this should now be properly fixed
